services:
  # MongoDB Service
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - wolfbot_network
    
  # WolfBot Service
  wolfbot-backend:
    build:
      context: .
    container_name: wolfbot-backend
    depends_on:
      - mongo_db
    networks:
      - wolfbot_network

volumes:
  mongo_data:

networks:
  wolfbot_network:
    driver: bridge